# https://github.com/morgoved/wazuh-helm/blob/main/charts/wazuh/README.md
# Cant get this working, will stay with docker but leaving for reference
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: &app wazuh
#   namespace: security
# spec:
#   interval: 15m
#   chart:
#     spec:
#       chart: wazuh
#       version: 0.1.5
#       interval: 30m
#       sourceRef:
#         kind: HelmRepository
#         name: wazuh-chart
#         namespace: flux-system

#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3

#   values:

#     fullnameOverride: wazuh

#     autoreload:
#       enabled: false

#     cert-manager:
#       enabled: false

#     indexer:
#       replicas: 3
#       updateStrategy: RollingUpdate

#       cred:
#         passwordHash: "$2y$12$Lrp8R7Kf.47nkZ/rEAprwunKJQ0MhjX5JCBjF5JCEXdFUH2bsQCwa"
#         password: ""

#     dashboard:
#       replicas: 1
      
#       cred:
#         password: ""
#         passwordHash: "$2y$12$1N4ryYwJM4a/YXMpiMhgRuW6QvfOXqoFhNsj6sZ59YnvCCk4GR8Xa"

#       ingress:
#         enabled: true
#         className: nginx
#         host: "wazuh.mafyuh.dev"
#         tls:
#           - secretName: mafyuh-dev-production-tls
#             hosts:
#               - "wazuh.mafyuh.dev"

#     wazuh:
#       env:
#         FILEBEAT_SSL_VERIFICATION_MODE: full
