apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: arr
spec:
  ingressClassName: nginx
  rules:
    - host: "bazarr.local.mafyuh.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headless-bazarr
                port:
                  number: 6767
  tls:
    - hosts:
        - "bazarr.local.mafyuh.com"
      secretName: local-mafyuh-com-production-tls