---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-secrets
  namespace: arr
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: NAS_IP
      remoteRef:
        key: "badc1823-c017-4d4a-a3a1-b372002be7dc"
    - secretKey: LOCAL_DOMAIN
      remoteRef:
        key: "94b4c24c-a5fe-43f7-80f1-b372002c9346"
    - secretKey: PUBLIC_DOMAIN
      remoteRef:
        key: "fa7aa6c7-7c9e-4db1-b5c7-b372002cd0a2"