---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner-iac-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: github_app_id
      remoteRef:
        key: "39d72a00-0890-4f92-b8c1-b381016aab39"
    - secretKey: github_app_installation_id
      remoteRef:
        key: "d4427a54-10c0-4df2-bb45-b381016b58e9"
    - secretKey: github_app_private_key
      remoteRef:
        key: "0aab8d2c-0794-42ef-9b74-b381016b8ea0"
