apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      sabnzbd:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteMany
              size: 500Mi
              storageClass: longhorn
              globalMounts:
                - path: /config

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: &group 65534
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              SABNZBD__PORT: &port 8080

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 20m
                memory: 200Mi
              limits:
                memory: 4000Mi

    service:
      app:
        primary: true
        controller: sabnzbd
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        className: nginx
        hosts:
          - host: "sabnzbd.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "sabnzbd.${LOCAL_DOMAIN}"
            secretName: local-mafyuh-dev-production-tls

    persistence:
      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data