apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: staging
  secretRef:
    name: flux-system
  url: https://git.mafyuh.dev/mafyuh/iac
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-staging

