services:
  portainer:
    image: portainer/portainer-ee@sha256:40691e7fbcc4effc4973eaad804b1874814fe8327f908d19da11468a45db20a8
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always

  vikunja:
    image: vikunja/vikunja@sha256:c400bdcb2ae4a78fccb9b463d01f96d1b2cfaef3484a4dd5c2a26e55eadc2d7a
    environment:
      VIKUNJA_SERVICE_PUBLICURL: $VIKUNJA_SERVICE_PUBLICURL
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_SERVICE_JWTSECRET: $VIKUNJA_SERVICE_JWTSECRET
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    ports:
      - 3456:3456
    volumes:
      - /home/mafyuh/vikunja/files:/app/vikunja/files
      - /home/mafyuh/vikunja/db:/db
    restart: unless-stopped

volumes:
  portainer_data:
