apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      radarr:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        statefulset:
          volumeClaimTemplates:
            - name: radarr-config
              accessMode: ReadWriteOnce
              size: 3Gi
              storageClass: longhorn
              globalMounts:
                - path: /config
        
        pod:
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - 1.1.1.1
              - 8.8.8.8

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.18.4.9674
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              RADARR__INSTANCE_NAME: *app
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: "https://radarr.${LOCAL_DOMAIN}"
              RADARR__THEME: dark
              RADARR__LOG_LEVEL: info

            probes:
              liveness:
                enabled: false

            resources:
              requests:
                cpu: 200m
                memory: 300Mi
              limits:
                memory: 512Mi

    service:
      app:
        primary: true
        controller: radarr
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        className: nginx
        hosts:
          - host: "radarr.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "radarr.${LOCAL_DOMAIN}"
            secretName: local-mafyuh-dev-production-tls

    persistence:
      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data
