---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname mafyuh.dev
    external-dns.alpha.kubernetes.io/hostname: *hostname
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.0.215
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.mafyuh.dev"
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-io
      protocol: HTTP
      port: 80
      hostname: "*.mafyuh.io"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.mafyuh.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: mafyuh-dev-production-tls