---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crd
  namespace: kube-system
spec:
  interval: 30m
  url: ghcr.io/wiremind/wiremind-helm-charts/gateway-api-crds
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gateway-api-crd
  namespace: &ns kube-system
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-crd
    namespace: kube-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gateway-api
  namespace: &ns kube-system
spec:
  targetNamespace: *ns
  path: ./kubernetes/components/gateway-api/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: gateway-api-crd
      namespace: kube-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m