---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname local.mafyuh.dev
    external-dns.alpha.kubernetes.io/hostname: *hostname
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.0.216
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.local.mafyuh.dev"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.local.mafyuh.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: local-mafyuh-dev-production-tls