apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:QndtEy4XC39CL3TC,iv:u5ziEPQzTPY6wvjdKPYVhiQppNJDW58NIz3vZ7l1ThA=,tag:YOrJu8XHzgzT2vm3HuvP9Q==,type:str]
    admin-password: ENC[AES256_GCM,data:aID5af9YekuRr1OqbqBxug==,iv:h8XgXCP0va49KJ5pq28ZoCIDR2uR+35sGrw+QjFuFzo=,tag:qVSoZypXn2JDmXfJDZOHmw==,type:str]
sops:
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkNFZ3ozeTlmQmRONHVJ
            NEVUN3VYd3BadDc4aTJrbUticmt5M3ZvYUZRCmN0TzVrVnQzZmZlOVZVZW9yL0hT
            SXlSUXkxRWpEN2YvNDVTalF4Y1ZBVlkKLS0tIGdlNnNJNUVhYVo1UmowZWVWS04w
            OXIzUCtLUGxYYlJ3YUJMUjhKZFBPK0EKffd5odPmuNxeK5s2eyITXzBHiN8WH+Xt
            075u+keUdlw8M/NYBuQMMpqZjh7FQ/7+lR6QvqZLxJZ+6qLaga6+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T06:16:00Z"
    mac: ENC[AES256_GCM,data:LEjq4LwmmIyvMGKJy2cq0CJOKAvIiS/h1PcdTF4TudOGcp8ZQHVv5YrfiJ4TWUWfIR2OJ7SjViifTfbmhxp9uElgY9nsjgFlDfo8TVrjaLFN0w5SboizwLXxQOgdCTUN67OraJmjGzm4AZSu/5GUEtZXsdbZ2zYP22aBMP7PKJk=,iv:HAbF24jhAhIDl+fOnZcZGrannGEQCDHTHzhEmeuwLNo=,tag:EC5S/0LJ8goakdDq/JQOEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
