apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-config
  namespace: default
data:
  additional-scrape-configs.yaml: |
    - job_name: 'node_exporter'
      scrape_interval: 15s
      static_configs:
        - targets: ['10.69.69.150:9100']
        - targets: ['10.0.0.15:9100']
        - targets: ['10.0.0.40:9100']
        - targets: ['10.69.69.127:9100']
        - targets: ['10.69.69.2:9100']

    - job_name: 'cadvisor'
      scrape_interval: 15s
      static_configs:
        - targets: ['10.69.69.150:9101']
        - targets: ['10.0.0.15:9101']
        - targets: ['10.0.0.40:9101']
        - targets: ['10.69.69.127:9101']
        - targets: ['10.69.69.2:9101']
