apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-config
  namespace: default
type: Opaque
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogJ25vZGVfZXhwb3J0ZXInCiAgc2NyYXBlX2ludGVydmFsOiAxNXMKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWycxMC42OS42OS4xNTA6OTEwMCddCiAgICAtIHRhcmdldHM6IFsnMTAuMC4wLjE1OjkxMDAnXQogICAgLSB0YXJnZXRzOiBbJzEwLjAuMC40MDo5MTAwJ10KICAgIC0gdGFyZ2V0czogWycxMC42OS42OS4xMjc6OTEwMCddCiAgICAtIHRhcmdldHM6IFsnMTAuNjkuNjkuMjo5MTAwJ10KCi0gam9iX25hbWU6ICdjYWR2aXNvcicKICBzY3JhcGVfaW50ZXJ2YWw6IDE1cwogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbJzEwLjY5LjY5LjE1MDo5MTAxJ10KICAgIC0gdGFyZ2V0czogWycxMC4wLjAuMTU6OTEwMSddCiAgICAtIHRhcmdldHM6IFsnMTAuMC4wLjQwOjkxMDEnXQogICAgLSB0YXJnZXRzOiBbJzEwLjY5LjY5LjEyNzo5MTAxJ10KICAgIC0gdGFyZ2V0czogWycxMC42OS42OS4yOjkxMDEnXQ==
