---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: matt@mafyuh.dev
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    email: matt@mafyuh.dev
                    apiTokenSecretRef:
                        name: cloudflare-token-secret
                        key: cloudflare-token
              selector:
                dnsZones:
                    - local.mafyuh.dev
                    - mafyuh.dev
