---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbox
  namespace: &ns networking
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/netbox/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m