---
services:
  cf-tunnel:
    restart: unless-stopped
    image: docker.mafyuh.xyz/cloudflare/cloudflared@sha256:31fc2956d49179f7fd230b030e702e40ade7ccc361d0f1079e4a56bc888678f9
    command: tunnel --no-autoupdate run --token $CF_TOKEN

  wallos:
    container_name: wallos
    image: bellamy/wallos:2.21.1
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '/home/mafyuh/wallos/db:/var/www/html/db'
      - '/home/mafyuh/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped