---
services:
  cf-tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared@sha256:c9206bb54b6eccf534d3ce748dffa9358f1d744f7605ef778383833e7a81a0e9
    command: tunnel --no-autoupdate run --token $CF_TOKEN

  wallos:
    container_name: wallos
    image: bellamy/wallos:2.24.0
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '/home/mafyuh/wallos/db:/var/www/html/db'
      - '/home/mafyuh/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped