---
services:
  cf-tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared@sha256:119c1712ba89bfb32a404ef6b949284519a99f3de5c1202f483a6800fd1c638e
    command: tunnel --no-autoupdate run --token $CF_TOKEN

  wallos:
    container_name: wallos
    image: bellamy/wallos:2.33.1
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '/home/mafyuh/wallos/db:/var/www/html/db'
      - '/home/mafyuh/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped