---
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin@sha256:59ff91bf3ec2cb7ee69fcc1426ef4d387eb17dc03c80e8232b5bb4fb0d6efc36
    container_name: jellyfin
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /home/mafyuh/jellyfin/config:/config
      - /mnt/thePoolShare/Media:/Media
      - /mnt/thePoolShare/Media/Youtube:/Media/Youtube:ro
      - /home/mafyuh/jellyfin/transcodes:/transcodes
      - /home/mafyuh/jellyfin/cache:/nvmecache
      - /home/mafyuh/jellyfin/metadata:/nvmemetadata
    ports:
      - 8096:8096
    restart: unless-stopped

  makemkv:
    image: jlesage/makemkv@sha256:39dccc4f82dc76668a78543ac7392a43b6bc6c069e1a3e47e8c058c6cb5f09b0
    container_name: makemkv
    ports:
      - 5800:5800
    volumes:
      - /docker/appdata/makemkv:/config:rw
      - /home/mafyuh/makemkv/storage:/storage:rw
      - /mnt/thePoolShare/Media/BR:/output:rw
    devices:
      - /dev/sr0:/dev/sr0
    privileged: true

  syncthing:
    image: ghcr.io/linuxserver/syncthing@sha256:d6502d919f49f16a80689ce92c211f945f1d64a34c0d3f23ecc27a2a4d1dd0ac
    container_name: syncthing
    hostname: JF
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/syncthing/config:/config
      - /docker/appdata/:/docker/appdata/
      - /home/mafyuh/jellyfin/:/home/mafyuh/jellyfin/
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
