apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-domain-config
    namespace: flux-system
data:
    LOCAL_DOMAIN: ENC[AES256_GCM,data:m6nkdDfRlhsgTcImO4u3LA==,iv:perK/v90gauuqG9O32x9+ZNDIHo7CmKVU6yGQei7QCo=,tag:gM97bgh74hFiTTx4f50Uyw==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:VmTTqtqN1cM7RQ==,iv:4y8m3q/SZkEoxtIkzLjxsBwg2u8KDSpTwJSx0YBFFIU=,tag:/pCFh0j0cYyRZOSsIigWmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVdMcTNYMTNmY2kvVnhW
            VHRmWGJQRlVjb1pkaUE4VkE2RVpoaVVIeTI0CnBVOFh0TVFrUWFYRmZiNy9CMWNW
            TlBVVkQyV0tZZEZiamFEak9aUS9mY2MKLS0tIG5LdUYrU0c5Zk1TYmNlOGd5NUhv
            K1cvYlZ5THZDaGU3QzlpSk9HR29LVjQKgTCBa08fZ1WExmwjrh08LwTdNeNjrQpA
            zbbNnI7LzcBggmfuQkBUMhVZx+LOU8IJKFb4K6i9Ihu1lqEfLmRZPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T04:59:48Z"
    mac: ENC[AES256_GCM,data:6e/p8RM7JytjOgn2p+v0KUmbjGRO0y3/z06jtyIiJIbiTGMbnAOUjBALC7r8QCC5kpLq8mnWi2nQINUH7MkeJmontFZrDBfmauGb0q6MfGTLfY6KtgtSxA20h45WkZgSKS09mILeHlFoE6yNGhlyjzn2Hpd+b4MVGx6BBBH7+rQ=,iv:uARk7mMsYw4m6q4LixsrtAdUTzPBUB7QnMiuRZQKhD4=,tag:DNxnKT2Dia0RZ1xzjHIqBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
