apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    LOCAL_DOMAIN: ENC[AES256_GCM,data:L184ECQQkdBcpivF/xFBDQ==,iv:xFr8h6s3Fqf2Nn3PxIruOM2woIUTYH0gYlHiX4r4DVQ=,tag:mrUhZeA1tuZX0xHya0kF3w==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:Xoz+xrvd3cdK/A==,iv:p0/e7n0YD/jZL8SMvuYJ6o4/RG90w7TRctg4eaO5MtQ=,tag:lYL//FkQGT9KzrJln7+w2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST05BUlZDTno2MGgzcW9P
            TkFlTnlZdXlnQ1pwVWVTZHowTzBGUjYrRG5NCnZqbmc3OUtjbDE3YzljMXhTemhC
            V2NDRDRKNG9pVzdMUC9jaS90aUlqNWMKLS0tIGRXeWE3QzFGeG15QTZna1ZwY2Zz
            Z05ESFNXekFVZGxMNzNReHoxcDNKKzQKcbXVz9Lko+hvwS+3Lbfp7AKpBp4xuiCJ
            lekvw9el/QXh1R0Bxaqk3TfHmZtUodHaR1wKdHkmLY88XsgPu4lUNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T05:16:16Z"
    mac: ENC[AES256_GCM,data:s8k7UkS3pADKHKZZ5H55hDt1j9ej1cuMH2HKebOEv/aEmti9A62NBYyB0q8SxrcNa3XflTqHZ2UviK/4ax+aZqbxnGSR2+h0cCz6y6U9YSnuua2qh2vOd87ygY+jlUjLOh30SCI60f9tRQIvORHV2IW8o7LBHxjZ2ZSIox0QYMo=,iv:d5T3Rsfdxmf+deZ+Zs5lRETFMOHqt1fG7ZNpj1f2SO4=,tag:hNYDzc0Ey3dq1hnx0rBvSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
