apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-config.yaml
  - cluster-secrets.yaml
  - longhorn-s3-secret.sops.yaml
  - recyclarr.yaml
  - secret.sops.yaml
  - terraform-cli-config-secret.sops.yaml