apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: arr
type: Opaque
stringData:
    RADARR_APT_KEY: ENC[AES256_GCM,data:ExNCoY5kWoUbZBxNnmCrFFfOa0bx2BD/koqX0EskCMM=,iv:BiphcBweetjC9NZgHN9RGois1r3HAiqvTotZbjs9ViE=,tag:EIXUZhcJXPJNdVsJGklAoQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:0FfjBWrWHrQJWjki5nXZG+nuM35jEq4DMOi0wzKVU8M=,iv:dlgFto0t+ED33jQkZ0GVyUhcEZnqPHMspAYOQ2FN5g0=,tag:B2RDZ+qdofxCcQaxFQNPog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWtGNHBNcCtIUDd0ZHNS
            K2lNMlFSMzlVRU1BUTNyWVdCTDh2UmY4VUJzCkk4Y1ZDcy8vTG84eTh6eXg0eWpO
            SFZqRjFrdjl6dWpJbTg3UnhNZ2JTOGsKLS0tIGRoT1cyK0phNXVwZEJ0M3VDcEpj
            KzdOczVjakovQlE1TkF4VUJORk5IdWsKx12AioJfcpmzCAbI+RwrJW1607YYsQbf
            N8EKX70kyhdlwyCMDwr7B0+eFAWsJAjsR+2Z91peXCxlfeVXu28eFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T05:23:57Z"
    mac: ENC[AES256_GCM,data:hKIi71rwjbZxHB82rBsihfRF1Euj6f/en7WqLKB51KjgCJczXspu6uJfnOD6Y/iacskM5Q9AZVd4X64p4YImjOLZph9wHnKvp+m6af5bM/Xwo8Sskg9NtsmFYBqEvp26+RcX+e8YEl5Fr4pHFZiTqIwIeQccvTunLRDXBT5i3Xs=,iv:y3PnaiXR4zZA9ZnElsNdpbqTsR6iiaRclVwhKavA/nw=,tag:RSxZ1Py5qvYT+baTcTNKcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
