apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: arr
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:UUsdVr598eyWGPx5GKyfmw2iOAT9ljr5vcgsYSE6s/Y=,iv:cMnQvSscgBqOVpBIJa6pzOdPKDmLFIbZIUtRp2T6Ldg=,tag:RmpFcUbWYZJF7HRlNbHdbA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:N/ad1zWIiVtH7aXVBshsJWMmiGT0moZ2hhMSnFUYB7s=,iv:Ov7nluBTVdvzlsAdFAzZBGrfrV9cxmVg0HPkGCtVG0c=,tag:ueY0XnEU0dLGk3EYKT0b2w==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:oy+rS3sbLn4DMmULBuS8FEb6f+227HFF9m6ElcBiRps=,iv:1OzQxnwVbTjlOq/9MY7+ijRN8/ZJLjI60vA8ej58SxQ=,tag:Q3SRHEvVm4+jIP+TCAeS7Q==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:UIigZqUAPgw1x7bgbKdyT7XYvR1Nt2YGObLpXK3uOCo=,iv:ipqxELejyf8c4j457JEbHSOlASZ82FVIYVVMtbzEsIo=,tag:w9MTallH/HeliDoXGkDaTw==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:J3H9zV3NeT4KeYlcL2Qg6aRDQmq4pc/G96qybRqDN3M=,iv:CjoqikqfGEwy/c4iZ6byT0G5HIBy72EczOgc0R7CmQ4=,tag:7qGYwjLg9e5W+CzviEP1uA==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:e1kj4ctmwPXpTmIh6nxFbTGxrRaf3sxKsqSa3wgw+ns=,iv:6PoiI6dfDiVatLV+6iBMTyC1jz7fSt8nQ6c73yMi/tg=,tag:QdnnElGDV8U8VuXWF0opjQ==,type:str]
sops:
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWtGNHBNcCtIUDd0ZHNS
            K2lNMlFSMzlVRU1BUTNyWVdCTDh2UmY4VUJzCkk4Y1ZDcy8vTG84eTh6eXg0eWpO
            SFZqRjFrdjl6dWpJbTg3UnhNZ2JTOGsKLS0tIGRoT1cyK0phNXVwZEJ0M3VDcEpj
            KzdOczVjakovQlE1TkF4VUJORk5IdWsKx12AioJfcpmzCAbI+RwrJW1607YYsQbf
            N8EKX70kyhdlwyCMDwr7B0+eFAWsJAjsR+2Z91peXCxlfeVXu28eFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T07:24:57Z"
    mac: ENC[AES256_GCM,data:iQTyB6+qLqi1g/SmxoayxbB1oIiM2RtE/D4b2BwyHFOLShQPBmEAHmMpobAq1hbyYvFMKxQ8SWM29JPYMmBgVkAB1VSckQCSGXIK00S+SYwriv0zMNHZRXuo8fuSt2jpyU3RGUvStwtzExaIk6b2yfaq9oPoXcGJchnRgkeu4MU=,iv:PrYr4Dnzf83Zfa9NGVrjU5fgA2GX4+0FMA2TVaMmdas=,tag:0zIvS4YFjm5DjdHqsTyXFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
