apiVersion: v1
kind: Secret
metadata:
    name: terraform-cli-config
    namespace: flux-system
type: Opaque
stringData:
    terraform.tfrc: ENC[AES256_GCM,data:1xRw5iogBZdUddAi2BKNqcRp6V0ottRNR2GIxT2u+9gMU4zr57wZxOirKil6oB/DGtzaZRFWNEfBM7Q2Nx0UMtvM7nOCsuFlq45Q2LbYlyJHR0FUX5g/kr31q+TAxoUGS5SckLK6/atxe1Dw+lDGYdzVB9Z+owsX0bcv48Csfm+4QW4heqcCs0Y/,iv:lyO5IrR54gtc7thfFGyqV3vFarmluzSNgBrkFK2kpd8=,tag:+cR7JK3NdZ4SB/HlXfoaSg==,type:str]
sops:
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dlZuOE9VUjNkS2pWVGR3
            QjU2M3hkcnJqNjBWRTZ2VElqVXYxVktQNnpjCmZTV1BxRk1ZM2hoNXVMZHlwWENH
            TU02TXdhTGZFRm5rL1ZUekozUzhVMUkKLS0tIC96ZkI0cTFoUUJaaStEa0lmcTN6
            Mk5PbEVVNDlmOGdBTGpvc3N2c1dLa3MKoZ2sELn2S/2HzCe6xVqHJXrHZer6lJPD
            Uo4AyUICjNPaDYll612qqKnrJ0WJ0K2Vh6Qs2IKrxHf1opsN3bbyEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T03:36:09Z"
    mac: ENC[AES256_GCM,data:G4re5bD5danYuhlG60bTGiVq4yfEjYMWfRDoi9tudzIQ3La2Nhh5Vyk1NPWx4CD+ZFvapnI2rEwffRZzi3bleermsxFk2rXQM64yAdUmakK/y66nmx4zmq63F9FE6NyqVN2yDYsu54B0tpP5qkHo4eTQ2vb+ByjVAxhW66friz0=,iv:58ijatZZzwiwN0T168299Cfsd3KG8CDdbgT2Fzy4ouM=,tag:OpHklCBVZmSCl1/E8qXdsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
