apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
  namespace: arr
  labels:
    app: recyclarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:7.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "125Mi"
              cpu: "75m"
          volumeMounts:
            - name: recyclarr-config-volume
              mountPath: /config/recyclarr.yaml
              subPath: recyclarr.yaml
      volumes:
        - name: recyclarr-config-volume
          configMap:
            name: recyclarr-config
