apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- actions-runner-system.yaml
- monitoring.yaml
- reflector.yaml
- nginx.yaml
- longhorn.yaml
- certman.yaml
- authentik.yaml
- arr.yaml
- networking.yaml
- tf-controller.yaml
- system-upgrade.yaml
