apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-kube-state-metrics-config
  namespace: monitoring
data:
  config.yaml: |
    spec:
      resources:
        # Flux Controller Deployments - for version information
        - groupVersionKind:
            group: apps
            version: v1
            kind: Deployment
          metricNamePrefix: gotk
          commonLabels:
            controller_type: flux
          labelSelectorFilter:
            - matchExpressions:
                - key: app.kubernetes.io/part-of
                  operator: In
                  values: [flux]
          metrics:
            - name: "controller_info"
              help: "Information about Flux controllers including version."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                controller_name: [metadata, labels, "app.kubernetes.io/component"]
                version: [metadata, labels, "app.kubernetes.io/version"]
                replicas: [spec, replicas]
                available_replicas: [status, availableReplicas]
                ready_replicas: [status, readyReplicas]
        # Flux Kustomization Resources
        - groupVersionKind:
            group: kustomize.toolkit.fluxcd.io
            version: v1
            kind: Kustomization
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Kustomization resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, lastAppliedRevision]
                source_name: [spec, sourceRef, name]
                source_namespace: [spec, sourceRef, namespace]
                path: [spec, path]
                prune: [spec, prune]
                interval: [spec, interval]
                retry_interval: [spec, retryInterval]
                timeout: [spec, timeout]
                observed_generation: [status, observedGeneration]
                last_applied_revision: [status, lastAppliedRevision]
                
        # Flux HelmRelease Resources with version info
        - groupVersionKind:
            group: helm.toolkit.fluxcd.io
            version: v2
            kind: HelmRelease
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmRelease resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, history, "0", chartVersion]
                chart_name: [status, history, "0", chartName]
                chart_app_version: [status, history, "0", appVersion]
                chart_ref_name: [spec, chartRef, name]
                chart_source_name: [spec, chart, spec, sourceRef, name]
                install_remediation_retries: [spec, install, remediation, retries]
                upgrade_remediation_retries: [spec, upgrade, remediation, retries]
                timeout: [spec, timeout]
                interval: [spec, interval]
                
        # Flux GitRepository Resources
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: GitRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux GitRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
                ref_branch: [spec, ref, branch]
                ref_tag: [spec, ref, tag]
                ref_commit: [spec, ref, commit]
                
        # Flux HelmRepository Resources  
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: HelmRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
                type: [spec, type]
                
        # Flux HelmChart Resources
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: HelmChart
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmChart resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                chart_name: [spec, chart]
                chart_version: [spec, version]
                source_name: [spec, sourceRef, name]
                
        # Flux OCIRepository Resources
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: OCIRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux OCIRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
                ref_tag: [spec, ref, tag]
                
        # Flux Image Automation Resources (if you use them)
        - groupVersionKind:
            group: image.toolkit.fluxcd.io
            version: v1
            kind: ImageRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux ImageRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                image: [spec, image]
                
        - groupVersionKind:
            group: image.toolkit.fluxcd.io
            version: v1
            kind: ImagePolicy
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux ImagePolicy resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                source_name: [spec, imageRepositoryRef, name]
                
        # Flux Notification Resources
        - groupVersionKind:
            group: notification.toolkit.fluxcd.io
            version: v1beta3
            kind: Provider
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Provider resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                suspended: [spec, suspend]
                type: [spec, type]