---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name n8n-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      data:
        N8N_PORT: "5678"
        N8N_PROTOCOL: http
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        N8N_HOST: "{{ .N8N_HOST }}"
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: "9c1edc74-25da-4ba3-ad30-b48800241fa9"
    - secretKey: N8N_HOST
      remoteRef:
        key: "f7ffc1de-f286-40b5-90f6-b461003cbf89"
