name: Add Docker Container
description: Steps to add a new Docker container to the repository
title: "[Add Container] <Container Name>"
labels:
  - docker
assignees:
  - mafyuh
body:
  - type: markdown
    attributes:
      value: |
        Follow the steps below to add a new Docker container. Copy the checklist and mark items as completed:
        ```
        - [ ] Add the Docker Compose file and necessary `.env` variables to the `.env` file.
        - [ ] If a new folder is created for the Docker Compose file, map the host in the Ansible workflow file:
          - Update at: [AnsibleCD.yml#L30](https://git.mafyuh.dev/mafyuh/iac/src/commit/22285723f6e5804b8737d6c8e9ea6915617c2271/.forgejo/workflows/ansibleCD.yml#L30)
        - [ ] Add the server IP to Bitwarden secrets and give Actions user access:
          - Navigate to [Vault](https://vault.bitwarden.com/#/sm/305f1e91-cd2b-411c-8acf-b1a3004a82b2)
        - [ ] Map the server IP in AnsibleCD workflow file:
          - Update at:
            - [Line 96](https://git.mafyuh.dev/mafyuh/iac/src/branch/main/.forgejo/workflows/ansibleCD.yml#L96)
            - [Line 116](https://git.mafyuh.dev/mafyuh/iac/src/branch/main/.forgejo/workflows/ansibleCD.yml#L116)
        ```
  - type: textarea
    attributes:
      label: Progress Checklist
      description: Copy the checklist above and paste it here to track your progress.
      placeholder: |
        Paste the checklist here and mark items as completed.
