name: Add Docker Container
description: Steps to add a new Docker container to the repository
title: "[Add Container] <Container Name>"
labels:
  - docker
assignees:
  - @mafyuh
body:
  - type: markdown
    attributes:
      value: |
        Follow the checklist below to add a new Docker container.
  - type: checklist
    attributes:
      label: Steps
      options:
        - label: Add the Docker Composeand any necessary env variables to the `.env` file.
        - label: If a new folder is created for the Docker Compose file, map the host in the Ansible workflow file:
          description: |
            Update the mapping at:
            [AnsibleCD.yml#L30](https://git.mafyuh.dev/mafyuh/iac/src/commit/22285723f6e5804b8737d6c8e9ea6915617c2271/.forgejo/workflows/ansibleCD.yml#L30).
        - label: Add the server IP to Bitwarden secrets. Give the Actions user access to secret
          description: |
            Navigate to [BWS](https://vault.bitwarden.com/#/sm/305f1e91-cd2b-411c-8acf-b1a3004a82b2) and add the server IP.
        - label: Map the server IP in AnsibleCD workflow file:
          description: |
            Update the IP at:
            - [Line 96](https://git.mafyuh.dev/mafyuh/iac/src/branch/main/.forgejo/workflows/ansibleCD.yml#L96)
            - [Line 116](https://git.mafyuh.dev/mafyuh/iac/src/branch/main/.forgejo/workflows/ansibleCD.yml#L116)