---
- name: Weekly System Update
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
        purge: yes
