apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: promtail
      version: 6.17.0
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: grafana-chart
        namespace: flux-system
  values:
    fullnameOverride: promtail