---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server/flux-ks.yaml
  - flux-operator/flux-ks.yaml
  - flux-instance/flux-ks.yaml
  - tofu-controller/flux-ks.yaml
  - external-secrets/flux-ks.yaml
  - gateway-api/flux-ks.yaml
  - rook-ceph/flux-ks.yaml
