apiVersion: v1
kind: ConfigMap
metadata:
    name: authentik-values
    namespace: authentik
data:
    values.yaml: ENC[AES256_GCM,data:O307JpuqBj0lNN+lG/4fyAwq/T27fFT7GtUTTXHM1LgRIKy/HepvN04exUaUx5reRK2jVIVDLys5ghEkPGLtvyxHYzU5Ay1v6J3Td+wZL8AVbSBHXJOQd/+A4VMeB6dh9Y45DZIbCqUBGmnih6o062JHyl7BCeZ343t1UQ+HSQlJEyuQiDIvEMG+KNz0aJ46IMS8w+PLuNKoRlfGw2QXu9/VMtiKhmdrpb18SyxjAmySlPH3UwipuxtDZJEhzDD0N3KetTt+DkOm7rBWwVmLbEpARhPGJZs4q9N7SpvO1nq7gv4Kz1oEEX4YwvmlMpzGrUeSSr94xRAzRDjyYQKB07A2BuAr85pAMog/yG2rfVurpPEsgM6ARJB/X4kiXRObDp48Xt38jJp3Ty+AokcYOWSaWMMRbJfmfZ5/t8NCt4jjjFkR7qAVbjEUUF0yU9ynse8ov31s6D6kAnfPJ2XXB98pq1p0/Hq4ZaCV52SSAp01C+JcwlOIydb5RM52hahECPq92Ih9Bi/Q+Pv8kV+rv9oYnSOwa+lIdjtoTLY+uxyknIdICaxs0KQqvCCtbI5FSP+6hWscygCJxe8Uyhcu/P9a/uvyMz9M049C5EylvND+QqSAcXvgjt2GqLkGe1IshkI5eDa/SUU/XhUHz+s3MH7iVsegu81NgEvhF2a7L29IoBLVHid4ucJccUGqFJ91rCizMBAcc6t2GVLaAOYNsuY/ESEMIBS8k8h2jsni+xPKxU9O9HYr7WG5RwYQ9QSY6ZNBm0GCtwoSyqGTyNPdcQJfBqE62SI0QS3nNa0HcuqCSF4ZqO+bkM2/StibfSTHLYVjtKQiIWCbLvIArSFQOEDVXZ9o+X3a1nKkfqCvwewe0GHMSpV3JrVvStybJOzJUv5d51w=,iv:hgj5wiSkC5BAwT2+XG5wepmoVVFxhFSF0Bmlx1T+Bug=,tag:F8cGwrskd1vY0bvk+pdF1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdG1aUk9aek5RVE4rZm5N
            ajhyc3NLKzF3Q3UrUE1RSFJsci9aMWNjbEQwCmhSNENJcWlaZUpxT3lqZmdOUWVo
            UDVwRC9vU0kwRDNXNk5VUVpMUTEwWDAKLS0tICtFL25FZFRaTEhPdWJhYmRYbFVt
            RndrQ2JxZnMxZlBIM3RHS0E1WTlZQzQK7oTkv/PG3poAdYnqXnzX3j5ZUgMa3GFB
            aQtceF96jKRltwPrnUgZZ5EadTaLyGAD30fqvUJ9/oP6NLe7kmsTWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T03:56:30Z"
    mac: ENC[AES256_GCM,data:BL5xeNKOBuVza4btSt81UaqGNEv83VsmkrSThpB7f8JUwcCTsX89J0P5rQNnXSF1uCZHtrcwtjN2R1x3yO4nfdiMCvZkYEj1AMrKWmD4TsC7faCszaqegiMvxD69FUSZ/8O3Kv0SC3RCk+Og/jv8YnEe+N+3DOAqyh6dbXQQtZU=,iv:WHpvFCpSRfwLWZlFvsRakSsDDktsOyzQ+bJbfjdyXug=,tag:X+RWg2FWlKXYXzolqZNLwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secret_key|password|hosts)$
    version: 3.9.4
