apiVersion: v1
kind: ConfigMap
metadata:
    name: authentik-values
    namespace: authentik
data:
    values.yaml: ENC[AES256_GCM,data:Zuyuzan5Aq8lbDI7EJNoPZUnBMLCimOhe4eopnWYR6WD7jXFNh9yx0elDBy0Gzr46RTPp8V/uL5RJHlKUgBVutgzGO1GIXoglS/3awkhLZ8f5yG9VOOHDdz1g1XPNX3IXhQGY3yj42xVuitKxp919oS+VyiqLozpyLiyWAhXIpfH0GozvIISMbHKc+9hqZ+h9bAFe5yAeByidUusRlzq0VtNMfftsYOLyt5lcPLGxn+32LkpmSV8qBtiP7AW5ZjUuXjU2Qoekscy5ncvjZXnUkIztO/xJrZ4ombgaClbP4JHEAyOZyi8hp+qR17k5mgOkt7v/1oflfE/Oir9/4q9QRNhlFDD3smuNyj7lCKFkvnWy7BD7W5m8VOz0UqleoFM9znOJ+836Or2y+emgkSYl5q6Ug5j8Lko9wzSVYIIrN8mOK4LB7afC3My4/YvyFCzCN/lX3vZ4sIGQEIzUKtD8l1gXofOHugHHp5Jsw6IzzGMBaY14ObJee4JXLCjMEZYH9l4HbO4iVqcK6NvGvpGqK3+A160Bx5GgMY2ZgyvUKyWNoHX9Kkq43JhqQF4SEz/l0id78AvXE8EWOMNvO+U92/fwtTetveaxAOAxeqGqor7nB6UO2p6vxJ2p12wG66rWAmUiTR+lAXdO1rAjtZ5xEU6UbNFF+PZi9sU8GynHC6EL/lU6FbCyDU2LvrJ68WZ9Hs0nZEOQ1NMmjEBEkJ9w87rRI5BTvT1WPOODjb4NnJ7c29tzUNVnzbshjnHyKqybeHb63zSEWnl+ixx7nDH4FOr1Jc4GUz/bnbYQZglrxrk7XmjSihSZKT1IkCwIJiNJSCYntBC51uZgbOtR2pm2qPI1wIYAtNl/lPxrnha59tE0v5ETirS9Lnzq7yPKsVF3Yji3qhqT9vM6pcxaX+esyKlgoH1yCll8bgPACYUt4P3BMiMjy4xtlQ2HC96ckeRIgwmm3Ykab1AZcSTPTA8rUQH4/dVzIS4v/Q6mTfsgZytmtg4MTLSrU5xf4G4sxYbxKqMImIZAOdUr1umCSz+D0L5w5U22Bf3/SWo4rf4mOAnCZkP/yBhEhR32L96hE/EwOw4yTNd72hBsWgpIRjHcM2ovPyLHMl5PLTNWrtG5oDAbMoJ6bYapUVCR7qMbTJkDfc6MWhyegFkfYl8iiow+1t2MMyIAOOB7N1o2E0QV9mRok7CR5nmWg==,iv:Eu+l9pWy3rCDLM3guZB7v/xLspDXeKdlWHlv0VyXCJQ=,tag:31B41sZuR/TmJU+e5Cep6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdG1aUk9aek5RVE4rZm5N
            ajhyc3NLKzF3Q3UrUE1RSFJsci9aMWNjbEQwCmhSNENJcWlaZUpxT3lqZmdOUWVo
            UDVwRC9vU0kwRDNXNk5VUVpMUTEwWDAKLS0tICtFL25FZFRaTEhPdWJhYmRYbFVt
            RndrQ2JxZnMxZlBIM3RHS0E1WTlZQzQK7oTkv/PG3poAdYnqXnzX3j5ZUgMa3GFB
            aQtceF96jKRltwPrnUgZZ5EadTaLyGAD30fqvUJ9/oP6NLe7kmsTWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T23:58:15Z"
    mac: ENC[AES256_GCM,data:CZaIg5AF4P13hoGRYRHRKtOBlkMPW0x9nrJ+xG1+xoyOR0z2QyH/wWe3L3zcpePh8yfKhsN9KCPjrXBYjw5FCDeA5fJjXuUcz3UnoOd4r6KEbQ3X4psohenI5xdPayu2an0x6JDcKYt24b3KWNqzhbSEBMNeaSZ3lJ7pCK5KacA=,iv:fxVjRakf6Cg24uRRUDROEA9G4jrcItEe0OD8T14S/Fo=,tag:PrGvhhiIlRwpLTAAzudd+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secret_key|password|hosts)$
    version: 3.9.4
