apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap-lb
  namespace: authentik
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: authentik-outpost-ldap
  ports:
    - name: ldap
      port: 389
      targetPort: 3389
      protocol: TCP