---
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: headlamp-authentik
  namespace: monitoring
spec:
  services:
    - name: headlamp
      namespace: monitoring
  resources:
    - "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      transport_api_version: V3
      http_service:
        server_uri:
          uri: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000
          cluster: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000
          timeout: 10s
        path_prefix: "/outpost.goauthentik.io/auth/nginx"
        authorization_request:
          allowed_headers:
            patterns:
              - exact: authorization
              - exact: cookie
              - exact: x-forwarded-for
              - exact: x-forwarded-proto
              - exact: x-forwarded-host
              - exact: x-original-url
          headers_to_add:
            - key: X-Forwarded-Proto
              value: https
            - key: X-Forwarded-Host
              value: "%REQ(:authority)%"
        authorization_response:
          allowed_upstream_headers:
            patterns:
              - exact: x-authentik-username
              - exact: x-authentik-groups
              - exact: x-authentik-email
              - exact: x-authentik-name
              - exact: x-authentik-uid
          allowed_client_headers:
            patterns:
              - exact: set-cookie
              - exact: location
      failure_mode_allow: false
