apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxmox.yaml
  - servarr.yaml
  - unifi.yaml
  - authentik.yaml
  - cloudflare.yaml
  - twingate.yaml
  - oracle.yaml
  - minio.yaml
