apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  interval: 5m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-repo
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
