apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/apps" 
  sourceRef:
    kind: GitRepository
    name: iac
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets