---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/apps" 
  sourceRef:
    kind: GitRepository
    name: iac
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/components" 
  sourceRef:
    kind: GitRepository
    name: iac
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/secrets"  
  sourceRef:
    kind: GitRepository
    name: iac
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: true
