apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/secrets"  
  sourceRef:
    kind: GitRepository
    name: iac
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: true
