---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/postgres-operator.crunchydata.com/pgadmin_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: oke-cluster
  namespace: databases
spec:
  users:
    - username: admin@mafyuh.io
      role: Administrator
      passwordRef:
        name: oke-cluster-crunchy-postgres
        key: PG_ADMIN_PASSWORD
  dataVolumeClaimSpec:
    storageClassName: oci-bv
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: oke-cluster
      postgresClusterName: oke-cluster
  config:
    settings:
      AUTHENTICATION_SOURCES: ["internal"]
  serviceName: oke-cluster-pgadmin
