- name: Docker Login
  hosts: "*"
  become: false
  vars:
    docker_password: "{{ lookup('bitwarden.secrets.lookup', '3726555b-0ffc-442b-b66a-b257016f6ab9', access_token=bw_access_token) }}"
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: mafyuh
        password: "{{ docker_password }}"
