---
- name: Reset and Pull Git Repository
  hosts: all
  tasks:
    - name: Ensure repo is in clean state
      ansible.builtin.git:
        repo: "https://github.com/mafyuh/iac.git"
        dest: "/home/{{ ansible_user }}/iac"
        version: main
        force: true
        update: true
        accept_hostkey: true
      environment:
        HOME: "/home/{{ ansible_user }}"
