- name: Install and start qemu-guest-agent
  hosts: "*"
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true

    - name: Start qemu-guest-agent service
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started
      become: true
