apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring.yaml
- reflector.yaml
- nginx.yaml
- longhorn.yaml
- certman.yaml
- authentik.yaml
- arr.yaml
- networking.yaml
