---
services:
  kasm:
    image: ghcr.io/linuxserver/kasm@sha256:4096b7de6ab7da4686be370c5408c7df60412fb4d9116820050fbdf3db279281
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
    volumes:
      - /docker/appdata/kasm:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
