---
services:
  kasm:
    image: ghcr.io/linuxserver/kasm@sha256:024796adcf2edd652bc30d93fbbbde0939e7a760db7309807b674674ec1623b1
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
    volumes:
      - /docker/appdata/kasm:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
