---
services:
  kasm:
    image: ghcr.io/linuxserver/kasm@sha256:8a1d0aaa54a77415a4abdcb0fc1c7f59813c1957a7507ccf4394f2d886e415d8
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME
      - DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD
    volumes:
      - /docker/appdata/kasm2:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
