---
services:
  kasm:
    image: ghcr.io/linuxserver/kasm@sha256:d92920b7ca216b7be402b07dccda34f11f34b37542600f69802285dcc8aafc4c
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
    volumes:
      - /docker/appdata/kasm:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
