---
services:
  kasm:
    image: ghcr.io/linuxserver/kasm@sha256:c68b21aab787c3a35e170438d6be2dcfaded038c09b7d96d06815d294ecd4241
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
    volumes:
      - /docker/appdata/kasm:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
