---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:bf170feeba5d14b4dcee91a7b93a14668e11c54fa81f28f9acaf3c137cd8c7a9
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
