---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-s3-backend
  namespace: flux-system
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: access_key
      remoteRef:
        key: "713c22ac-210f-42bf-ab4e-b371017dd0dd"
    - secretKey: secret_key
      remoteRef:
        key: "444d8094-5d11-4b3b-92a7-b371017e2269"