---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    awsPackage:
      install: false
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.0-rc.5
        pullPolicy: IfNotPresent
      grpc:
        maxMessageSize: 30
    logLevel: debug
    allowBreakTheGlass: false
    clusterDomain: cluster.local
    concurrency: 24
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m