---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: admin-user
      remoteRef:
        key: "998a1402-19e2-45cd-91b3-b371015b816f"
    - secretKey: admin-password
      remoteRef:
        key: "c98a3540-e2ee-465d-9c48-b371015bc053"