---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate-secrets
  namespace: networking
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: TWINGATE_ACCESS_TOKEN
      remoteRef:
        key: "016937dc-1079-4ca9-872d-b372000db0bb"
    - secretKey: TWINGATE_REFRESH_TOKEN
      remoteRef:
        key: "a7de33d9-07ac-4faf-b8e7-b372000df776"