---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: connector
      version: 0.1.31
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: twingate-chart
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: twingate-values