apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 6.30.1
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: grafana-chart
        namespace: flux-system
  values:
    loki:
      auth_enabled: false

      server:
        http_listen_port: 3100
        grpc_listen_port: 9096

      commonConfig:
        path_prefix: /tmp/loki
        replication_factor: 1
      storage:
        bucketNames:
          chunks: ""
          ruler: ""
          admin: ""
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      schemaConfig:
        configs:
          - from: 2020-10-24
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h