apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector-system
spec:
  interval: 5m
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: 7.1.288
      sourceRef:
        kind: HelmRepository
        name: reflector-repo
        namespace: flux-system
  values:
    replicaCount: 1