apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      speedtestExporter:
        containers:
          app:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            env:
              TZ: America/New_York
            resources:
              requests:
                cpu: 15m
                memory: 50M
              limits:
                memory: 100M
    service:
      app:
        controller: speedtestExporter
        ports:
          http:
            port: 9798
    serviceMonitor:
      main:
        enabled: true
        serviceName: speedtest-exporter
        endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 30m
          scrapeTimeout: 3m