---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: monitoring
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: N8N_GOTIFY_ALERTM
      remoteRef:
        key: "d031e7a1-3226-49e6-ae67-b484015fc764"
