---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner/ks.yaml
  - alloy/ks.yaml
  - arr/
  - authentik/ks.yaml
  - blackbox/ks.yaml
  - cert-manager/ks.yaml
  - cilium/ks.yaml
  - gatus/ks.yaml
  - grafana/ks.yaml
  - headlamp/ks.yaml
  - kromgo/ks.yaml
  - loki/ks.yaml
  - netbox/ks.yaml
  - nginx/ks.yaml
  - prometheus/ks.yaml
  - reflector/ks.yaml
  - tuppr/ks.yaml
  - twingate/ks.yaml
  - unpoller/ks.yaml
