apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: arr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"