---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-instance
  namespace: flux-system
spec:
  path: ./kubernetes/components/flux-instance/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config

  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m