apiVersion: v1
kind: Secret
metadata:
    name: flux-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:phs4fJFZdCc4rAw8mHTO07GnEMaqx/u6hMckMZj7yeNoF1jwonbloOHtgw6tVST9WtfE1/DbZ3vWGgZpCNu3NQ==,iv:izlFGJ6DK2UMte/237udJBNdBvHNGCFMADsXxjWVFjk=,tag:JgH0lvINEnvt33+h15105w==,type:str]
sops:
    age:
        - recipient: age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobDFWT1VacVViTngzcWUw
            UVlUb2RjdkxENDl2VTcrYlU2Ym1jbHgyTGc0CkxMZVMzMk9KWnl1M3lnMnZsMXo2
            a0dQakpjM2diVHAzN0tWZWVYTTJpNTgKLS0tIFQ4UEJPclRxbEZKQ0M4THhlQUww
            UHAwazV4Q0tqYlVzZzR3S2JXY0RlcWcKqiiw5nST35SVoMgk0/5jsILKENJ9xvyY
            cL4aYBOGo5sgWcG3LBb4/GsIKkcSnBnbusp0W7LrpXFsvNm+P+x2Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T07:15:24Z"
    mac: ENC[AES256_GCM,data:j4F7PavPmDxjKH6dOX0T+iAQ9O1dtruarOdUEU9M9SI2K8qY5UEBTcC39V/w5WQ3R0Y+VqX9FmkIA/nSeBPhU85fXrdV3/kkD65ZdYy98SvLFkdL0seehv1NVWabCPWIuS35ODiJFNlgTQqD2k5vQtn8eTMDwxOp90ygs9me3ZQ=,iv:A8h8l+plOogEEk7xV8q81IT5zf7KJXCNSGhbPPYfP70=,tag:zCt5zgM0aIYOXj9FJ4A/bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
