---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oke-cluster
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  path: ./kubernetes/oke/cluster
  sourceRef:
    kind: GitRepository
    name: iac
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
