---
# yaml-language-server: $schema=https://github.com/Twingate/helm-charts/raw/refs/heads/master/stable/connector/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app twingate
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: connector
      version: 0.1.31
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: twingate-chart
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:

    resources:
      requests:
        cpu: 50m
        memory: 200Mi
    
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    
    connector:
      network: "mafyuh"
      accessToken: ${TWINGATE_ACCESS_TOKEN}
      refreshToken: ${TWINGATE_REFRESH_TOKEN}