---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: "5b626bee-4b9c-46b4-92fe-b4840015ba3b"
