name: Auto-Update Talos

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force update'
        required: false
        default: false
        type: boolean
  pull_request:
    types: [closed]
    branches: [ main ]
    paths:
      - 'kubernetes/talos/talconfig.yaml'

jobs:
  auto-update:
    runs-on: self-hosted
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup environment
      run: |
        # Ensure tools are available
        which talhelper || { echo "talhelper not found"; exit 1; }
        which talosctl || { echo "talosctl not found"; exit 1; }
    
    - name: Run auto-update
      run: |
        cd scripts
        ./auto-update-talos.sh
      env:
        TALOSCONFIG: /home/mafyuh/iac/kubernetes/talos/clusterconfig/talosconfig
