---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
  namespace: networking
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cloudflare-dns-secret
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: "5b626bee-4b9c-46b4-92fe-b4840015ba3b"
    - secretKey: CF_ZONE_ID
      remoteRef:
        key: "88bf0db8-89ec-4761-a734-b484002d4fab"
